Class {
	#name : 'LePharoBPatternRewriteSnippetScopeChanged',
	#superclass : 'LeSnippetContentChanged',
	#instVars : [
		'scope'
	],
	#category : 'BPatterns-LepiterSnippet',
	#package : 'BPatterns-LepiterSnippet'
}

{ #category : 'as yet unclassified' }
LePharoBPatternRewriteSnippetScopeChanged >> scope [
	^ scope
]

{ #category : 'as yet unclassified' }
LePharoBPatternRewriteSnippetScopeChanged >> scope: aString [
	scope := aString
]
