Class {
	#name : 'LePharoBPatternRewriteSnippetSearchChanged',
	#superclass : 'LeSnippetContentChanged',
	#instVars : [
		'search'
	],
	#category : 'BPatterns-LepiterSnippet',
	#package : 'BPatterns-LepiterSnippet'
}

{ #category : 'as yet unclassified' }
LePharoBPatternRewriteSnippetSearchChanged >> search [
	^ search
]

{ #category : 'as yet unclassified' }
LePharoBPatternRewriteSnippetSearchChanged >> search: aString [
	search := aString
]
