"
I represent a source code rewrite rule using two pattern blocks:

```Smalltalk
	| any any2 |
	[[ any isNil ifTrue: any2 ] -> [ any ifNil: any2 ]] brewrite
```

The main outer block encloses an association of two pattern blocks: the search pattern and the replace pattern. The variables and selectors inside the rewrite block can be used as a pattern to match particular AST nodes.

By default the following objects are automatically configured as **ANY** pattern to match any AST node:
- variables started with **any** word
- selectors where a keyword is started with **any** word

To narrow the filter represented by a pattern you have to configure it using **#with:** message:

```
	| any any2 |
	[[ any isNil ifTrue: any2 ] -> [ any ifNil: any2 ]] 
		brewrite with: [ anyVar ] -> [:pattern | pattern beVariable ]
```

Underhood my instances consists of two BPatterns: #searchPattern and #rewritePattern. The configuration from #with: message is applied to both of them.

See the package comment for the full details about the patterns configuration.

Once you have a brewrite instance you can preview the system changes it represents and then apply it using the refactoring UI:

```Smalltalk
	[:any :any2 | any isNil ifTrue: any2 ] brewrite preview.

	[:any | [ any printString asString ] -> [ any printString ]] brewrite 
		previewForClass: BPatternMethodQueryTest.
```

"
Class {
	#name : 'BPatternRewrite',
	#superclass : 'Object',
	#instVars : [
		'searchPattern',
		'rewritePattern'
	],
	#category : 'BPatterns',
	#package : 'BPatterns'
}

{ #category : 'instance creation' }
BPatternRewrite class >> fromBlock: definitionBlock [
	| ruleAssoc searchPattern rewritePattern |
	ruleAssoc := definitionBlock value.
	searchPattern := ruleAssoc key bpattern.
	rewritePattern := ruleAssoc value bpattern.
	^self fromPattern: searchPattern to: rewritePattern
]

{ #category : 'instance creation' }
BPatternRewrite class >> fromPattern: searchPattern to: rewritePattern [
	searchPattern isSequenceNode = rewritePattern isSequenceNode 
		ifFalse: [ searchPattern isSequenceNode
				ifTrue: [ rewritePattern adoptToSequenceNode ]
				ifFalse: [ searchPattern adoptToSequenceNode ]].
	^self new 
		searchPattern: searchPattern;
		rewritePattern: rewritePattern 
]

{ #category : 'printing' }
BPatternRewrite >> displayStringOn: aStream [ 
	
	aStream nextPutAll: '[ '.
	searchPattern displayStringOn: aStream.
	aStream nextPutAll: ' ] -> [ '.
	rewritePattern displayStringOn: aStream.
	aStream nextPutAll: ' ]'
]

{ #category : 'rewriting' }
BPatternRewrite >> preview [
	| methods |
	methods := searchPattern users.
	^self previewForMethods: methods
]

{ #category : 'rewriting' }
BPatternRewrite >> previewForClass: aClass [
	| methods |
	methods := searchPattern usersInClass: aClass.
	^self previewForMethods: methods
]

{ #category : 'rewriting' }
BPatternRewrite >> previewForMethods: methods [
	| changes preview |
	changes := self changeForMethods: methods.
	preview := StRefactoringPreviewPresenter for: changes scopes: {ClyNavigationEnvironment currentImageScope}.
	preview openModal
]

{ #category : 'printing' }
BPatternRewrite >> printOn: aStream [
	super printOn: aStream.
	
	aStream nextPut: $(.
	self displayStringOn: aStream.
	aStream nextPut: $)
]

{ #category : 'rewriting' }
BPatternRewrite >> rewriteAST: anAST [
	^searchPattern rewriteAST: anAST with: rewritePattern
]

{ #category : 'rewriting' }
BPatternRewrite >> rewriteMethod: aMethod [
	^self rewriteAST: aMethod sourceNode copy
]

{ #category : 'accessing' }
BPatternRewrite >> rewritePattern [

	^ rewritePattern
]

{ #category : 'accessing' }
BPatternRewrite >> rewritePattern: anObject [

	rewritePattern := anObject
]

{ #category : 'accessing' }
BPatternRewrite >> searchPattern [

	^ searchPattern
]

{ #category : 'accessing' }
BPatternRewrite >> searchPattern: anObject [

	searchPattern := anObject
]

{ #category : 'initialization' }
BPatternRewrite >> with: configSpecs [ 
	searchPattern with: configSpecs.
	rewritePattern with: configSpecs
]
